services:
  searxng:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SEARXNG_BASE_URL=http://localhost:8080
        - SEARXNG_UWSGI_WORKERS=4
        - SEARXNG_UWSGI_THREADS=4
        - PORT=8080
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://localhost:8080
      - PORT=8080
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
      - SEARXNG_SECRET_KEY=my-custom-secret-key-from-env
    volumes:
      - ./searxng:/etc/searxng
    restart: unless-stopped
    networks:
      - searxng-network

networks:
  searxng-network:
    driver: bridge 