use_default_settings: true
server:
  secret_key: "248761c39005d33050fec8bd6b40a170f133ff471f71a0e262154a5903c7d3e3"
search:
  # 控制搜索结果的过滤程度。值为 0 表示不进行过滤，1 表示中度过滤，2 表示严格过滤。
  safe_search: 0
  autocomplete: ""
  favicon_resolver: ""
  # 定义了默认的搜索语言。设置为 "auto" 会根据浏览器的语言自动检测
  default_lang: "en"
  languages:
    - all
  # 控制搜索引擎能返回的页面数量，0 表示无限制
  max_page: 0  
  ban_time_on_fail: 0
  max_ban_time_on_fail: 0
  formats:
    - json

outgoing:
  # 提高默认超时时间，减少请求失败
  request_timeout: 6.0
  # 设置最大超时上限
  max_request_timeout: 15.0
  # 增加连接池容量以处理并发请求
  pool_connections: 150
  # 增加保持连接的数量
  pool_maxsize: 30
  # 启用HTTP2提高性能
  enable_http2: true

doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'
  doai.io: 'https://dissem.in/'
  sci-hub.se: 'https://sci-hub.se/'
  sci-hub.st: 'https://sci-hub.st/'
  sci-hub.ru: 'https://sci-hub.ru/'

default_doi_resolver: 'oadoi.org'

engines:

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    # 增加请求间隔时间（秒）
    request_interval: 10.0
    # 设置请求速率限制,限制每秒只能发送0.2个请求（约每5秒一个请求）
    rate_limit: 0.1
    # 使用随机化的 User-Agent
    use_mobile_ui: false
    # 添加悬挂时间（当遇到错误时暂停使用的时间）
    suspended_time: 300
    disabled: true

  - name: duckduckgo images
    engine: duckduckgo_extra
    categories: [images, web]
    ddg_category: images
    shortcut: ddi
    disabled: true

  - name: duckduckgo videos
    engine: duckduckgo_extra
    categories: [videos, web]
    ddg_category: videos
    shortcut: ddv
    disabled: true

  - name: duckduckgo news
    engine: duckduckgo_extra
    categories: [news, web]
    ddg_category: news
    shortcut: ddn
    disabled: true

  - name: duckduckgo weather
    engine: duckduckgo_weather
    shortcut: ddw
    disabled: true

  - name: google
    engine: google
    shortcut: go
    # 增加请求间隔
    request_interval: 10.0
    # 限制请求速率
    rate_limit: 0.1
    # 被限制时的暂停时间(秒)
    suspended_time: 300
    # 使用随机化的请求头
    use_mobile_ui: false
    # 避免传递敏感信息
    safe_search: true
    # 可选:限制结果数量
    results_per_page: 10

  - name: google images
    engine: google_images
    shortcut: goi
    #   dali:
    #     matrix:
    #       query: ['Dali Christ']
    #       lang: ['en', 'de', 'fr', 'zh-CN']
    #     result_container:
    #       - ['one_title_contains', 'Salvador']

  - name: google news
    engine: google_news
    shortcut: gon

  - name: google videos
    engine: google_videos
    shortcut: gov

  - name: google scholar
    engine: google_scholar
    shortcut: gos

  - name: google play apps
    engine: google_play
    categories: [files, apps]
    shortcut: gpa
    play_categ: apps
    disabled: true

  - name: google play movies
    engine: google_play
    categories: videos
    shortcut: gpm
    play_categ: movies
    disabled: true

  - name: bing
    engine: bing
    shortcut: bi
    disabled: true

  - name: bing images
    engine: bing_images
    shortcut: bii
    disabled: true

  - name: bing news
    engine: bing_news
    shortcut: bin
    disabled: true

  - name: bing videos
    engine: bing_videos
    shortcut: biv
    disabled: true

  - name: brave
    engine: brave
    shortcut: br
    time_range_support: true
    paging: true
    categories: [general, web]
    brave_category: search
    # brave_spellcheck: true
    disabled: true

  - name: brave.images
    engine: brave
    network: brave
    shortcut: brimg
    categories: [images, web]
    brave_category: images
    disabled: true

  - name: brave.videos
    engine: brave
    network: brave
    shortcut: brvid
    categories: [videos, web]
    brave_category: videos
    disabled: true

  - name: brave.news
    engine: brave
    network: brave
    shortcut: brnews
    categories: news
    brave_category: news
    disabled: true
