# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
general:
  debug: true
search:
  formats:
    - html
    - json
    - csv
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable
  secret_key: "my-custom-secret-key-from-env"
  limiter: true  # enable this for public usage
  image_proxy: true
ui:
  static_use_hash: true
# Redis configuration - can be enabled if Railway Redis addon is used
# redis:
#   url: ${REDIS_URL}
